Makefile: remove unused parameter
Avoid the following error:

  error: argument unused during compilation:
    '-L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform'
    [-Werror,-Wunused-command-line-argument]

Signed-off-by: Derrick Stolee <dstolee@microsoft.com>